jdk:
  - openjdk6
rvm:
  - 2.0.0
notifications:
  recipients:
    - jari.bakken@gmail.com
  irc: "irc.freenode.net#selenium"
before_script:
  - ./install.sh
env:
  - localhost=localhost.localdomain DISPLAY=:99 WD_SPEC_DRIVER=chrome chrome_server=./chrome-linux/chromedriver chrome_binary=./chrome-linux/chrome
matrix:
  allow_failures:
    - rvm: ruby-head