jdk:
  - openjdk6
rvm:
  - 1.9.3
  - 2.0.0
  - jruby
  - rbx-19mode
  - ruby-head
notifications:
  recipients:
    - jari.bakken@gmail.com
  irc: "irc.freenode.net#selenium"
before_script:
  - ./install.sh
env:
  - localhost=travis DISPLAY=:99 WD_SPEC_DRIVER=unit
  - localhost=travis DISPLAY=:99 WD_SPEC_DRIVER=firefox
  - localhost=travis DISPLAY=:99 WD_SPEC_DRIVER=chrome chrome_server=./chrome-linux/chromedriver chrome_binary=./chrome-linux/chrome
  - localhost=travis DISPLAY=:99 WD_SPEC_DRIVER=remote
  - localhost=travis DISPLAY=:99 WD_SPEC_DRIVER=rc_client SELENIUM_RC_TIMEOUT=120
matrix:
  allow_failures:
    - rvm: ruby-head